CREATE DATABASE IF NOT EXISTS `spring-test`;
-- create user
CREATE USER 'user'@'localhost' IDENTIFIED BY 'test';
GRANT ALL ON spring-test.* TO 'user'@'localhost';

USE `spring-test`;

CREATE TABLE USER_DETAILS (
USERNAME VARCHAR(10) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL,
PRIMARY KEY (USERNAME)
);

CREATE TABLE USER_AUTH (
USERNAME VARCHAR(10) NOT NULL,
AUTHORITY VARCHAR(10) NOT NULL,
FOREIGN KEY (USERNAME) REFERENCES USER_DETAILS(USERNAME)
);
